---
before_script:
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-geometry.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-grid.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-istl.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-localfunctions.git
  - duneci-install-module https://gitlab.dune-project.org/staging/dune-python.git
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
  - duneci-install-module https://gitlab.dune-project.org/dune-fem/dune-fem.git

debian:10  gcc:c++17:
  image: duneci/debian:10
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.gcc.c++17}

ubuntu:18.04--gcc:
  image: duneci/ubuntu:18.04
  script: duneci-standard-test

ubuntu:18.04--clang:
  image: duneci/ubuntu:18.04
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.clang}

ubuntu:18.04--python:
  image: duneci/ubuntu:18.04
  variables: {DUNECI_OPTS: /duneci/opts.gcc}
  script:
    - cd /duneci/modules/
    - export DUNE_PY_DIR=${PWD}/cache/
    - export PYTHONPATH=${PWD}/dune-python/build-cmake/python:${PWD}/dune-alugrid/build-cmake/python:${PWD}/dune-fem/build-cmake/python:${PWD}/dune-fem/build-cmake/python:${PWD}/dune-fem-dg/build-cmake/python:${PWD}/dune-polygongrid/build-cmake/python:${PWD}/dune-spgrid/build-cmake/python:${PWD}/dune-vem/build-cmake/python:${PWD}/opm-grid/build-cmake/python
    - dunecontrol
    - cd /duneci/modules/dune-fem-dg/pydemo/euler
    - python paper.py
  variables: {DUNECI_OPTS: /duneci/opts.clang}
