---
variables:
  DUNE_CMAKE_FLAGS:   "-DDUNE_ENABLE_PYTHONBINDINGS=ON -DDUNE_GRID_GRIDTYPE_SELECTOR=ON -DDUNE_MAX_TEST_CORES=4 -DBUILD_SHARED_LIBS=TRUE -DDUNE_PYTHON_INSTALL_LOCATION=none -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_LATEX=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Alberta=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Vc=TRUE -DCMAKE_DISABLE_DOCUMENTATION=TRUE"
  DUNECI_CMAKE_FLAGS: $DUNE_CMAKE_FLAGS
  DUNE_PY_DIR:        /duneci/modules/dune-py
  # adding this actually leads to the test failure seen in the core modules
  # don't know why this is required here but not for core modules - magic?
  DUNECI_PARALLEL:      "6"
  PYTHONPATH:         "/duneci/modules/dune-common/build-cmake/python:/duneci/modules/dune-geometry/build-cmake/python:/duneci/modules/dune-grid/build-cmake/python:/duneci/modules/dune-istl/build-cmake/python:/duneci/modules/dune-alugrid/build-cmake/python:/duneci/modules/dune-fem/build-cmake/python:$CI_PROJECT_DIR/build-cmake/python"

before_script:
  - . /duneci/bin/duneci-init-job
    #- python3 -m venv /duneci/modules/dune-pip
    #- source /duneci/modules/dune-pip/bin/activate
    #- pip install --upgrade pip
    #- pip install ufl numpy matplotlib mpi4py portalocker
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-geometry.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-grid.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-istl.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-localfunctions.git
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
  - duneci-install-module https://gitlab.dune-project.org/dune-fem/dune-fem.git

debian-11-gcc-9-17:
  image: registry.dune-project.org/docker/ci/debian:11
  script:
    #- source /duneci/modules/dune-pip/bin/activate
      # issue with setup-dunepy: dune-fem-dg not yet build so dependency in dune-fem-dg fails
      # - python /duneci/modules/dune-python/bin/setup-dunepy.py --opts=$CI_PROJECT_DIR/scripts/opts/ci-gcc.opts install
    - duneci-standard-test
  variables:
    DUNECI_TOOLCHAIN:  gcc-9-17
    DUNE_CONTROL_PATH:  /duneci/modules:$CI_PROJECT_DIR
    #DUNE_CMAKE_FLAGS:   "-DDUNE_ENABLE_PYTHONBINDINGS=OFF -DDUNE_MAX_TEST_CORES=4 -DBUILD_SHARED_LIBS=TRUE -DDUNE_PYTHON_INSTALL_LOCATION=none -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_LATEX=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Alberta=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Vc=TRUE -DCMAKE_DISABLE_DOCUMENTATION=TRUE"
  tags: [stuttgart2]

ubuntu-20.04-clang-10-17:
  image: registry.dune-project.org/docker/ci/ubuntu:20.04
  script:
    - duneci-standard-test
  variables:
    DUNECI_TOOLCHAIN:  clang-10-20
    DUNE_CONTROL_PATH: /duneci/modules:$CI_PROJECT_DIR
    #DUNE_CMAKE_FLAGS:   "-DDUNE_ENABLE_PYTHONBINDINGS=OFF -DDUNE_MAX_TEST_CORES=4 -DBUILD_SHARED_LIBS=TRUE -DDUNE_PYTHON_INSTALL_LOCATION=none -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_LATEX=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Alberta=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Vc=TRUE -DCMAKE_DISABLE_DOCUMENTATION=TRUE"
  tags: [stuttgart1]

ubuntu-20.04-gcc-9-17:
  image: registry.dune-project.org/docker/ci/ubuntu:20.04
  script:
    - duneci-standard-test
  variables:
    DUNECI_TOOLCHAIN:  gcc-9-17
    DUNE_CONTROL_PATH: /duneci/modules:$CI_PROJECT_DIR
  tags: [stuttgart1]
