---
before_script:
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-geometry.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-grid.git
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
  - duneci-install-module https://gitlab.dune-project.org/dune-fem/dune-fem.git

debian:10  gcc:c++17:
  image: duneci/debian:10
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.gcc.c++17}

ubuntu:18.04--gcc:
  image: duneci/ubuntu:18.04
  script: duneci-standard-test

ubuntu:18.04--clang:
  image: duneci/ubuntu:18.04
  script: duneci-standard-test
  variables: {DUNECI_OPTS: /duneci/opts.clang}
