---
variables:
  DUNECI_OPTS:       $CI_PROJECT_DIR/scripts/opts/ci-gcc.opts
  # dune-python will use DUNE_OPTS when building stuff
  # doen't seem to be true anymore - uses DUNE_CMAKE_FLAGS instead
  # DUNE_OPTS:         $CI_PROJECT_DIR/opts.gcc
  DUNE_CMAKE_FLAGS:   -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DDUNE_MAX_TEST_CORES=4 -DBUILD_SHARED_LIBS=TRUE -DDUNE_PYTHON_INSTALL_LOCATION=none -DCMAKE_DISABLE_FIND_PACKAGE_LATEX=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Alberta=TRUE -DCMAKE_DISABLE_DOCUMENTATION=TRUE -DCMAKE_CXX_FLAGS='-O3 -g -Wall -fdiagnostics-color=always'
  DUNECI_CMAKE_FLAGS: -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DDUNE_MAX_TEST_CORES=4 -DBUILD_SHARED_LIBS=TRUE -DDUNE_PYTHON_INSTALL_LOCATION=none -DCMAKE_DISABLE_FIND_PACKAGE_LATEX=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_Alberta=TRUE -DCMAKE_DISABLE_DOCUMENTATION=TRUE -DCMAKE_CXX_FLAGS='-O3 -g -Wall -fdiagnostics-color=always'
  DUNECI_TOOLCHAIN:  gcc-7-17
  DUNE_CONTROL_PATH: /duneci/modules:$CI_PROJECT_DIR
  DUNE_PY_DIR:       /duneci/modules/dune-py
  PYTHONPATH:        "/duneci/modules/dune-python/build-cmake/python:/duneci/modules/dune-fem/build-cmake/python:/duneci/modules/dune-alugrid/build-cmake/python:/duneci/modules/dune-py/dune-py/python:/duneci/modules/dune-py/python:$CI_PROJECT_DIR/build-cmake/python"

before_script:
  - python3 -m venv /duneci/modules/dune-pip
  - source /duneci/modules/dune-pip/bin/activate
  - pip install --upgrade pip
  - pip install ufl numpy matplotlib mpi4py portalocker
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-geometry.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-grid.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-istl.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-localfunctions.git
  - duneci-install-module https://gitlab.dune-project.org/staging/dune-python.git
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
  - duneci-install-module https://gitlab.dune-project.org/dune-fem/dune-fem.git

    # debian:10  gcc:c++17:
debian-10-gcc-8-17:
  image: duneci/debian:10
  script:
    # activate virtual env
    - source /duneci/modules/dune-pip/bin/activate
      # issue with setup-dunepy: dune-fem-dg not yet build so dependency in dune-fem-dg fails
      # - python /duneci/modules/dune-python/bin/setup-dunepy.py --opts=$CI_PROJECT_DIR/scripts/opts/ci-gcc.opts install
    - duneci-standard-test

#ubuntu:18.04--gcc:
#  image: duneci/ubuntu:18.04
#  script: duneci-standard-test

